# Generated by Django 3.0.7 on 2020-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('market_cap', models.FloatField(default=0)),
            ],
        ),
    ]
