# Generated by Django 3.0.7 on 2020-07-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='likes',
        ),
        migrations.AddField(
            model_name='coin',
            name='social_score',
            field=models.FloatField(default=0),
        ),
    ]
