# Generated by Django 3.0.7 on 2020-07-29 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0002_auto_20200723_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCoin',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
                ('social_score', models.FloatField(default=0)),
                ('market_cap', models.FloatField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical coin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
