# Generated by Django 3.0.7 on 2020-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20200728_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='social_score_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoin',
            name='market_cap_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoin',
            name='price_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoin',
            name='social_score_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
