# Generated by Django 3.0.7 on 2020-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20200728_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_btc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_btc_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='total_volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='total_volume_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoin',
            name='price_btc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcoin',
            name='price_btc_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcoin',
            name='total_volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoin',
            name='total_volume_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
